version: '3'

services:
  reverse:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/nginx/auth:/etc/nginx/auth
      - /etc/nginx/templates:/etc/nginx/templates
      - /etc/nginx:/etc/nginx
      - /etc/nginx/snippets:/etc/nginx/snippets/
      - /etc/nginx/ssl/private:/etc/ssl/private/
      - /etc/nginx/ssl/certs:/etc/ssl/certs/
      - /etc/nginx/data/www:/data/www
      - /etc/nginx/cache:/var/cache/nginx
    environment:
      - NGINX_HOST=127.0.0.1
      - NGINX_PORT=80
    network_mode: bridge
